cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls')),
                  path('captcha/', include('captcha.urls')),
                  path('', include('shop.urls', namespace='shop')),  # копируем все urls из приложения shop
                  path('api-auth/', include('rest_framework.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'filters', FiltersViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'tags', TagViewSet)
router.register(r'products', ProductViewSet)
router.register(r'reviews', ReviewViewSet)

# используем namespacing для удобства. Теперь, к примеру, the product_list URL будет доступен, как shop:product_list в других частях Django проекта.
app_name = 'shop'

urlpatterns = [
        path('', ShopHome.as_view(), name='product_list'),
        path('projects/', ObjectList.as_view(), name='projects'),
        path('search/', SearchList.as_view(), name='search'),
        path('object/<slug:object_slug>/', SearchListProject.as_view(), name='search_list_project'),
        path('profile/', profile, name='profile'),
        path('property/', my_objects, name='property'),
        path('booking/', booking, name='booking'),
        path('category/<slug:category_slug>/', ShopCategory.as_view(), name='product_list_by_category'),
        path('category/<slug:category_slug>/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
        path('add_category/', add_category, name='add_category'),
        path('about/', about, name='about'),
        path('add_product/', add_product, name='add_product'),
        path('login/', LoginUser.as_view(), name='login'),
        path('accounts/login/', LoginUser.as_view(), name='login'),
        path('logout/', logout_user, name='logout'),
        path('register/', RegisterUser.as_view(), name='register'),
        path('product/add/', ProductCreateView.as_view(), name='add_product_view'),
        path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
        path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
        path('tag/add/', TagCreateView.as_view(), name='tag_add'),
        path('api/', include(router.urls)),
    ]

shop/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Min, Count, Q
from loguru import logger
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, FormView, DetailView, DeleteView, UpdateView

from orders.models import OrderItem, Order
from .forms import RegisterUserForm, LoginUserForm, FeedbackForm, ReviewForm, ProductForm, CategoryForm, TagForm, \
    UserProfileForm, ObjectFilterForm
from .models import *
from .permissions import IsStaffOrReadOnly
from .serializers import FiltersSerializer, CategorySerializer, TagSerializer, ProductSerializer, ReviewSerializer
from .utils import DataMixin
from cart.forms import CartAddProductForm
from rest_framework import viewsets

logger.add("debug.log", format="{time} {level} {message}", level="DEBUG", rotation="10 MB")


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


def is_employee(user):
    return user.is_staff


class ShopHome(DataMixin, ListView):
    model = Object
    template_name = 'shop/product/list.html'
    context_object_name = 'objects'

    def get_queryset(self):
        # Получаем объекты, у которых есть неоплаченные квартиры
        objects_with_apartments = Object.objects.filter(frame__product__isnull=False).distinct() \
            .exclude(frame__product__order_items__order__paid=True)

        # Вычисляем минимальную цену квартиры для каждого объекта
        objects_with_min_price = []
        for obj in objects_with_apartments:
            min_price = Product.objects.filter(frame__object=obj).aggregate(Min('price'))['price__min']
            obj.min_price = min_price
            objects_with_min_price.append(obj)

        return objects_with_min_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем минимальные цены в контекст
        context['objects'] = context['objects']
        return context


class ObjectList(ListView):
    model = Object
    template_name = 'shop/product/project_list.html'
    context_object_name = 'objects'

    def get_queryset(self):
        form = ObjectFilterForm(self.request.GET)
        objects_with_apartments = Object.objects.filter(frame__product__isnull=False).distinct()

        if form.is_valid():
            category = form.cleaned_data.get('category')
            min_price = form.cleaned_data.get('min_price')
            max_price = form.cleaned_data.get('max_price')

            if category:
                objects_with_apartments = objects_with_apartments.filter(frame__product__category__slug=category)

            objects_with_apartments = objects_with_apartments.exclude(frame__product__order_items__order__paid=True)

            if min_price:
                objects_with_apartments = objects_with_apartments.filter(frame__product__price__gte=min_price)

            if max_price:
                objects_with_apartments = objects_with_apartments.filter(frame__product__price__lte=max_price)

        objects_with_min_price = []
        for obj in objects_with_apartments:
            min_price = obj.frame_set.first().product_set.filter(available=True).aggregate(min_price=Min('price'))[
                'min_price']
            obj.min_price = min_price
            objects_with_min_price.append(obj)

        return objects_with_min_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = ObjectFilterForm(self.request.GET)
        return context


class SearchList(ListView):
    model = Product
    template_name = 'shop/product/search_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        # Извлекаем параметры из запроса
        category = self.request.GET.get('category')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')

        # Фильтруем продукты, исключая оплаченные и находящиеся в заказах
        products = Product.objects.exclude(order_items__order__paid=True) \
            .annotate(order_count=Count('order_items', filter=Q(order_items__order__paid=True))) \
            .exclude(order_count__gt=0)

        # Применяем фильтры, если они переданы в запросе
        if category:
            products = products.filter(category__slug=category)

        if min_price:
            products = products.filter(price__gte=min_price)

        if max_price:
            products = products.filter(price__lte=max_price)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Добавьте любую дополнительную логику контекста, если необходимо

        return context


class SearchListProject(ListView):
    template_name = 'shop/product/search_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        object_slug = self.kwargs['object_slug']
        current_object = get_object_or_404(Object, slug=object_slug)

        # Извлекаем параметры из запроса
        category = self.request.GET.get('category')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')

        # Фильтруем продукты по текущему объекту и условиям
        products = Product.objects.filter(frame__object=current_object) \
            .exclude(order_items__order__paid=True) \
            .annotate(order_count=Count('order_items', filter=Q(order_items__order__paid=True))) \
            .exclude(order_count__gt=0)

        # Применяем фильтры, если они переданы в запросе
        if category:
            products = products.filter(category__slug=category)

        if min_price:
            products = products.filter(price__gte=min_price)

        if max_price:
            products = products.filter(price__lte=max_price)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = Object.objects.filter(slug=self.kwargs['object_slug']).first()

        # Группировка продуктов по корпусам
        grouped_products = {}
        for product in context['products']:
            frame_number = product.frame.number
            if frame_number not in grouped_products:
                grouped_products[frame_number] = {'frame': product.frame, 'apartments': []}
            grouped_products[frame_number]['apartments'].append(product)

        # Преобразование словаря в список для удобства отображения в шаблоне
        context['grouped_products'] = list(grouped_products.values())

        return context


class ProductCreateView(StaffRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/product/crud/add_product_view.html'
    success_url = reverse_lazy('shop:product_list')


class ProductUpdateView(StaffRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/product/crud/update_product.html'
    success_url = reverse_lazy('shop:product_list')


class ProductDeleteView(StaffRequiredMixin, DeleteView):
    model = Product
    template_name = 'shop/product/crud/delete_product.html'
    success_url = reverse_lazy('shop:product_list')

    def delete(self, request, *args, **kwargs):
        # Логическое удаление
        self.object = self.get_object()
        self.object.available = False
        self.object.save()
        return redirect(self.success_url)


class ProductDetailView(DataMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'shop/product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        context['review_form'] = ReviewForm()
        context['cart_product_form'] = CartAddProductForm()
        context = self.get_user_context(**context)
        return context

    def post(self, request, category_slug, slug):
        product = self.get_object()
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            cleaned_form = review_form.cleaned_data
            author_name = "Анонимный пользователь"
            Review.objects.create(
                product=product,
                author=author_name,
                rating=cleaned_form['rating'],
                text=cleaned_form['text']
            )
            return redirect('shop:product_detail', category_slug=category_slug, slug=slug)

        context = self.get_context_data()
        context['review_form'] = review_form
        return self.render_to_response(context)


class ShopCategory(DataMixin, ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products'
    allow_empty = False  # генерация ошибки 404 если  нет товаров в категории

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = str(context['products'][0].category)
        return dict(list(context.items()))

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'shop/product/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Регистрация')
        context['form_first'] = RegisterUser.form_class
        return dict(list(context.items()) + list(user_context.items()))

shop/templates/shop/profile/booking.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Бронирование
{% endblock %}
{% block content %}
    <div class="container-fluid mt-4"> <!-- Добавлен отступ сверху -->
        <div class="row">
            <!-- Панель слева с переключателями страниц -->
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:profile' %}">
                                <i class="fas fa-user"></i> Профиль
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:property' %}">
                                <i class="fas fa-home"></i> Мои объекты
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'shop:booking' %}">
                                <i class="fas fa-shopping-cart"></i> Бронирование
                            </a>
                        </li>
                        <!-- Добавьте дополнительные пункты меню, если необходимо -->
                    </ul>
                </div>
            </nav>

            <div class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <!-- Основное содержимое страницы -->
                <div class="container-fluid">
                    <div class="row">
                    {% if bookings %}
                        {% for booking in bookings %}
                        <div class="col-6">
                            <div class="card mb-4">
                                <div class="row g-0">
                                    <div class="col-md-4">
                                        <img src="{% if booking.product.image %}{{ booking.product.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}" class="img-fluid rounded-start" alt="Product Image">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ booking.product.title }}</h5>
                                            <p class="card-text">Стоимость от {{ booking.product.price }} €</p>
                                            <p class="card-text">Цена за м² от {% widthratio booking.product.price booking.product.area 1 %} €</p>
                                            <p class="card-text">Корпус {{ booking.product.frame.number }}, Этаж {{ booking.product.floors }} из {{ booking.product.frame.floors }}</p>
                                            <p class="card-text">Заселение до {{ booking.product.frame.object.date }}</p>
                                            <form method="post" action="{% url 'shop:booking' %}">
                                                {% csrf_token %}
                                                <input type="hidden" name="order_id" value="{{ booking.order.id }}">
                                                <button type="submit" class="btn btn-primary">Оплатить</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                        <div class="col-10 text-center">
                            <p class="display-4">Бронирований нет</p>
                            <i class="fas fa-shopping-cart fa-5x"></i>
                        </div>
                    {% endif %}
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
  body {
    display: flex;
    flex-direction: column;
    min-height: 100vh; /* 100% высоты видимой области окна браузера */
  }

  .container-fluid {
    flex: 1; /* Растягиваем основной контейнер на всю доступную высоту */
  }

  /* Добавленные стили для футера */
  footer {
    margin-top: auto; /* Магическая магия для размещения футера внизу */
  }
</style>
{% endblock %}

shop/templates/shop/profile/my_object.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Бронирование
{% endblock %}
{% block content %}
    <div class="container-fluid mt-4"> <!-- Добавлен отступ сверху -->
        <div class="row">
            <!-- Панель слева с переключателями страниц -->
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:profile' %}">
                                <i class="fas fa-user"></i> Профиль
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:property' %}">
                                <i class="fas fa-home"></i> Мои объекты
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'shop:booking' %}">
                                <i class="fas fa-shopping-cart"></i> Бронирование
                            </a>
                        </li>
                        <!-- Добавьте дополнительные пункты меню, если необходимо -->
                    </ul>
                </div>
            </nav>

            <div class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <!-- Основное содержимое страницы -->
                <div class="container-fluid">
                    <div class="row">
                    {% if propertys %}
                        {% for property in propertys %}
                        <div class="col-6">
                            <div class="card mb-4">
                                <div class="row g-0">
                                    <div class="col-md-4">
                                        <img src="{% if property.product.image %}{{ property.product.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}" class="img-fluid rounded-start" alt="Product Image">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ property.product.title }}</h5>
                                            <p class="card-text">Стоимость от {{ property.product.price }} €</p>
                                            <p class="card-text">Цена за м² от {% widthratio property.product.price property.product.area 1 %} €</p>
                                            <p class="card-text">Корпус {{ property.product.frame.number }}, Этаж {{ property.product.floors }} из {{ property.product.frame.floors }}</p>
                                            <p class="card-text">Заселение до {{ property.product.frame.object.date }}</p>
                                            <form method="post" action="{% url 'shop:property' %}">
                                                {% csrf_token %}
                                                <input type="hidden" name="order_id" value="{{ property.order.id }}">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                        <div class="col-10 text-center">
                            <p class="display-4">Пока нет объектов</p>
                            <i class="fas fa-home fa-5x"></i>
                        </div>
                    {% endif %}
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
  body {
    display: flex;
    flex-direction: column;
    min-height: 100vh; /* 100% высоты видимой области окна браузера */
  }

  .container-fluid {
    flex: 1; /* Растягиваем основной контейнер на всю доступную высоту */
  }

  /* Добавленные стили для футера */
  footer {
    margin-top: auto; /* Магическая магия для размещения футера внизу */
  }
</style>
{% endblock %}

shop/templates/shop/profile/profile.html
{% extends 'shop/base.html' %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <!-- Панель слева с переключателями страниц -->
      <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar mt-4">
        <div class="position-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:profile' %}">
                    <i class="fas fa-user"></i> Профиль
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:property' %}">
                    <i class="fas fa-home"></i> Мои объекты
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'shop:booking' %}">
                    <i class="fas fa-shopping-cart"></i> Бронирование
                </a>
            </li>
            <!-- Добавьте дополнительные пункты меню, если необходимо -->
          </ul>
        </div>
      </nav>

      <!-- Основное содержимое страницы -->
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <!-- Заголовок Профиль и кнопка выхода -->
        <div class="d-flex justify-content-between align-items-center mt-4">
          <h3 class="mt-4 mx-auto">Профиль</h3>
          <a href="{% url 'shop:logout' %}" class="btn btn-danger mt-5 mx-auto">Выход</a>
        </div>

        <!-- Карточка с данными пользователя -->
        <div class="card mt-4 mx-auto" style="max-width: 600px;">
          <div class="card-body">
            <h5 class="card-title mb-4">Личные данные</h5>
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="text-center mt-4">
                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </div>
  </div>
    <style>
  body {
    display: flex;
    flex-direction: column;
    min-height: 100vh; /* 100% высоты видимой области окна браузера */
  }

  .container-fluid {
    flex: 1; /* Растягиваем основной контейнер на всю доступную высоту */
  }

  /* Добавленные стили для футера */
  footer {
    margin-top: auto; /* Магическая магия для размещения футера внизу */
  }
</style>
{% endblock %}