cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls')),
                  path('captcha/', include('captcha.urls')),
                  path('', include('shop.urls', namespace='shop')),  # копируем все urls из приложения shop
                  path('api-auth/', include('rest_framework.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'filters', FiltersViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'tags', TagViewSet)
router.register(r'products', ProductViewSet)
router.register(r'reviews', ReviewViewSet)

# используем namespacing для удобства. Теперь, к примеру, the product_list URL будет доступен, как shop:product_list в других частях Django проекта.
app_name = 'shop'

urlpatterns = [
        path('', ShopHome.as_view(), name='product_list'),
        path('projects/', ObjectList.as_view(), name='projects'),
        path('search/', SearchList.as_view(), name='search'),
        path('object/<slug:object_slug>/', SearchListProject.as_view(), name='search_list_project'),
        path('profile/', profile, name='profile'),
        path('property/', my_objects, name='property'),
        path('booking/', booking, name='booking'),
        path('category/<slug:category_slug>/', ShopCategory.as_view(), name='product_list_by_category'),
        path('category/<slug:category_slug>/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
        path('add_category/', add_category, name='add_category'),
        path('about/', about, name='about'),
        path('add_product/', add_product, name='add_product'),
        path('login/', LoginUser.as_view(), name='login'),
        path('accounts/login/', LoginUser.as_view(), name='login'),
        path('logout/', logout_user, name='logout'),
        path('register/', RegisterUser.as_view(), name='register'),
        path('product/add/', ProductCreateView.as_view(), name='add_product_view'),
        path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
        path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
        path('tag/add/', TagCreateView.as_view(), name='tag_add'),
        path('api/', include(router.urls)),
    ]

shop/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Min, Count, Q
from loguru import logger
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, FormView, DetailView, DeleteView, UpdateView

from orders.models import OrderItem, Order
from .forms import RegisterUserForm, LoginUserForm, FeedbackForm, ReviewForm, ProductForm, CategoryForm, TagForm, \
    UserProfileForm, ObjectFilterForm
from .models import *
from .permissions import IsStaffOrReadOnly
from .serializers import FiltersSerializer, CategorySerializer, TagSerializer, ProductSerializer, ReviewSerializer
from .utils import DataMixin
from cart.forms import CartAddProductForm
from rest_framework import viewsets

logger.add("debug.log", format="{time} {level} {message}", level="DEBUG", rotation="10 MB")


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


def is_employee(user):
    return user.is_staff


class ShopHome(DataMixin, ListView):
    model = Object
    template_name = 'shop/product/list.html'
    context_object_name = 'objects'

    def get_queryset(self):
        # Получаем объекты, у которых есть неоплаченные квартиры
        objects_with_apartments = Object.objects.filter(frame__product__isnull=False).distinct() \
            .exclude(frame__product__order_items__order__paid=True)

        # Вычисляем минимальную цену квартиры для каждого объекта
        objects_with_min_price = []
        for obj in objects_with_apartments:
            min_price = Product.objects.filter(frame__object=obj).aggregate(Min('price'))['price__min']
            obj.min_price = min_price
            objects_with_min_price.append(obj)

        return objects_with_min_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем минимальные цены в контекст
        context['objects'] = context['objects']
        return context


class ObjectList(ListView):
    model = Object
    template_name = 'shop/product/project_list.html'
    context_object_name = 'objects'

    def get_queryset(self):
        form = ObjectFilterForm(self.request.GET)
        objects_with_apartments = Object.objects.filter(frame__product__isnull=False).distinct()

        if form.is_valid():
            category = form.cleaned_data.get('category')
            min_price = form.cleaned_data.get('min_price')
            max_price = form.cleaned_data.get('max_price')

            if category:
                objects_with_apartments = objects_with_apartments.filter(frame__product__category__slug=category)

            objects_with_apartments = objects_with_apartments.exclude(frame__product__order_items__order__paid=True)

            if min_price:
                objects_with_apartments = objects_with_apartments.filter(frame__product__price__gte=min_price)

            if max_price:
                objects_with_apartments = objects_with_apartments.filter(frame__product__price__lte=max_price)

        objects_with_min_price = []
        for obj in objects_with_apartments:
            min_price = obj.frame_set.first().product_set.filter(available=True).aggregate(min_price=Min('price'))[
                'min_price']
            obj.min_price = min_price
            objects_with_min_price.append(obj)

        return objects_with_min_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = ObjectFilterForm(self.request.GET)
        return context


class SearchList(ListView):
    model = Product
    template_name = 'shop/product/search_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        # Извлекаем параметры из запроса
        category = self.request.GET.get('category')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')

        # Фильтруем продукты, исключая оплаченные и находящиеся в заказах
        products = Product.objects.exclude(order_items__order__paid=True) \
            .annotate(order_count=Count('order_items', filter=Q(order_items__order__paid=True))) \
            .exclude(order_count__gt=0)

        # Применяем фильтры, если они переданы в запросе
        if category:
            products = products.filter(category__slug=category)

        if min_price:
            products = products.filter(price__gte=min_price)

        if max_price:
            products = products.filter(price__lte=max_price)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Добавьте любую дополнительную логику контекста, если необходимо

        return context


class SearchListProject(ListView):
    template_name = 'shop/product/search_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        object_slug = self.kwargs['object_slug']
        current_object = get_object_or_404(Object, slug=object_slug)

        # Извлекаем параметры из запроса
        category = self.request.GET.get('category')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')

        # Фильтруем продукты по текущему объекту и условиям
        products = Product.objects.filter(frame__object=current_object) \
            .exclude(order_items__order__paid=True) \
            .annotate(order_count=Count('order_items', filter=Q(order_items__order__paid=True))) \
            .exclude(order_count__gt=0)

        # Применяем фильтры, если они переданы в запросе
        if category:
            products = products.filter(category__slug=category)

        if min_price:
            products = products.filter(price__gte=min_price)

        if max_price:
            products = products.filter(price__lte=max_price)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = Object.objects.filter(slug=self.kwargs['object_slug']).first()

        # Группировка продуктов по корпусам
        grouped_products = {}
        for product in context['products']:
            frame_number = product.frame.number
            if frame_number not in grouped_products:
                grouped_products[frame_number] = {'frame': product.frame, 'apartments': []}
            grouped_products[frame_number]['apartments'].append(product)

        # Преобразование словаря в список для удобства отображения в шаблоне
        context['grouped_products'] = list(grouped_products.values())

        return context


class ProductCreateView(StaffRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/product/crud/add_product_view.html'
    success_url = reverse_lazy('shop:product_list')


class ProductUpdateView(StaffRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/product/crud/update_product.html'
    success_url = reverse_lazy('shop:product_list')


class ProductDeleteView(StaffRequiredMixin, DeleteView):
    model = Product
    template_name = 'shop/product/crud/delete_product.html'
    success_url = reverse_lazy('shop:product_list')

    def delete(self, request, *args, **kwargs):
        # Логическое удаление
        self.object = self.get_object()
        self.object.available = False
        self.object.save()
        return redirect(self.success_url)


class ProductDetailView(DataMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'shop/product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        context['review_form'] = ReviewForm()
        context['cart_product_form'] = CartAddProductForm()
        context = self.get_user_context(**context)
        return context

    def post(self, request, category_slug, slug):
        product = self.get_object()
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            cleaned_form = review_form.cleaned_data
            author_name = "Анонимный пользователь"
            Review.objects.create(
                product=product,
                author=author_name,
                rating=cleaned_form['rating'],
                text=cleaned_form['text']
            )
            return redirect('shop:product_detail', category_slug=category_slug, slug=slug)

        context = self.get_context_data()
        context['review_form'] = review_form
        return self.render_to_response(context)


class ShopCategory(DataMixin, ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products'
    allow_empty = False  # генерация ошибки 404 если  нет товаров в категории

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = str(context['products'][0].category)
        return dict(list(context.items()))

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'shop/product/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Регистрация')
        context['form_first'] = RegisterUser.form_class
        return dict(list(context.items()) + list(user_context.items()))

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Shop{% endblock %}</title>
    <link href="{% static 'shop/css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css'  %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
  </head>

<body>
    <!-- Navbar-->
    {% block mainmenu %}
    <div class="header-white">
        <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search fixed-top bg-light">
            <div class="container">
                <a class="navbar-brand text-dark" href="{% url 'shop:product_list' %}">
                    <span style="color:#0d6efd"><b>FutureBuilders Enterprise</b></span>
                </a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="nav navbar-nav">

                        <li class="nav-item" role="presentation">
                            <a class="nav-link active text-dark" href="{% url 'shop:projects' %}">Объекты</a>
                        </li>
                        {% if user.is_staff %}
                        <li class="nav-item" role="presentation">
                            <a class="nav-link active text-dark" href="http://127.0.0.1:8001/admin/">
                                Менеджер
                            </a>
                        </li>
                        {% endif %}
                        <li class="nav-item" role="presentation">
                            <a class="nav-link active text-dark" href="http://127.0.0.1:8001/api/">API</a>
                        </li>
                    </ul>
                    <form class="form-inline mr-auto" target="_self">
                    </form>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'shop:profile' %}"><span style="color:#4169E1;">{{ user.username }} &nbsp</span></a>
                    {% else %}
                    <a class="btn btn-light action-button" role="button" href="{% url 'shop:login' %}">Войти</a>&nbsp
                    <a class="btn btn-light action-button" role="button" href="{% url 'shop:register' %}">Зарегистрироваться</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    {% endblock mainmenu %}
    <!--End Navbar-->

    <!-- Заголовок с брендом-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">


            </div>
        </div>
    </header>
    <!-- Конец заголовка-->

    <div id="content">
        {% block content %} {% endblock %}
    </div>

    <!-- Пагинация -->
    <br>
    {% if page_obj.has_other_pages %}
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            </li>
            {% endif %}
            {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-item active" aria-current="{{ p }}">
                <span class="page-link">{{ p }}</span>
            </li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
            <li class="page-item">
                <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    <!-- Конец пагинации -->

</div>

<!-- Footer-->
<footer class="py-5 bg-dark footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Django website by Alexei Fedotov
        </p>
    </div>
</footer>
<!-- End footer-->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>